/*
 * This source file was generated by the Gradle 'init' task
 */
package me.noynto.avting;

import com.rabbitmq.client.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.charset.StandardCharsets;

public class LetterBox {

    private static final Logger LOGGER = LoggerFactory.getLogger(LetterBox.class);
    private static final String PARIS_QUEUE_NAME = "PARIS";

    public static void main(String[] args) {
        LOGGER.info("Letter box is opening.");
        ConnectionFactory connectionFactory = new ConnectionFactory();
        try (
                Connection connection = connectionFactory.newConnection();
                Channel channel = connection.createChannel()
        ) {
            channel.queueDeclare(PARIS_QUEUE_NAME, false, false, false, null);
            LOGGER.info("Letter box is opened.");
            String letterToParis = "Dear Old Friend, I've heard that you live in Paris now?";
            channel.basicPublish("", PARIS_QUEUE_NAME, null, letterToParis.getBytes(StandardCharsets.UTF_8));
            LOGGER.info("Letter is sent.");
        } catch (Exception e) {
            LOGGER.error(e.getMessage(), e);
        } finally {
            LOGGER.info("Letter box is closed.");
        }
    }
}
